server:
  port: 8443
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: secret
  http2:
    enabled: true

spring:
  main:
#    should be disabled in prod
    lazy-initialization: true

oaat:
 jwt:
  secret: mysecret
  expiration: 28800
