= One At A Time API doc

This is the documentation for the API, with curl command, request and response format for each endpoint.

== Message Operations

=== GET all Messages
operation::findAllMessages[snippets='curl-request,http-request,http-response,response-fields']

//=== GET Cow by name
//operation::findByNameCow[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== GET Message by ID
operation::findByIdMessage[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== POST (save) Message
operation::saveMessage[snippets='curl-request,http-request,http-response,request-fields,response-headers']

== User Operations

=== GET User by ID
operation::findByIdUser[snippets='curl-request,http-request,http-response,path-parameters,response-fields']

=== POST authentication
operation::auth[snippets='curl-request,http-request,http-response,request-fields,response-fields']

=== POST (save) User
operation::saveUser[snippets='curl-request,http-request,http-response,request-fields,response-headers']
